### ISSUE TITLE
Find duplicate images applies on all files

### ISSUE THREAD

**Issue by bharath2020** [buchireddy/simple-hacks#1]
Here is the example 

Renaming  ./28916_ios_email_with_attachment 2.zip ./28916_ios_email_with_attachment_2.zip
Renaming  ./29485_c_243_digo_de_barras_no_delphi_para_ios (1).ZIP ./29485_c_243_digo_de_barras_no_delphi_para_ios_1_.ZIP
Renaming  ./adt-bundle-mac-x86_64-20140702 (1).zip ./adt-bundle-mac-x86_64-20140702_1_.zip
Renaming  ./AMP-SDK-latest.bin (1).zip ./AMP-SDK-latest.bin_1_.zip
Renaming  ./AMP-SDK-latest.bin (2).zip ./AMP-SDK-latest.bin_2_.zip
Renaming  ./AMP-SDK-latest.bin (3).zip ./AMP-SDK-latest.bin_3_.zip
Renaming  ./AMP-SDK-latest.bin (4).zip ./AMP-SDK-latest.bin_4_.zip

**Comment by buchireddy** [comment]
The script first renames the files if they have any special characters like '(', ')' or spaces in them. Were you expecting something different? Did you run into any issue due to this?

**Comment by buchireddy** [comment]
@bharath2020 I have fixed the script not to rename the files since the user might not want that. Please try it now and let me know if you have any feedback.

**Comment by bharath2020** [comment]
fixed
