### ISSUE TITLE
Find duplicate images python script crashes after scanning .xcodeproj file

### ISSUE THREAD

**Issue by bharath2020** [buchireddy/simple-hacks#2]
Renaming  ./29485_c_243_digo_de_barras_no_delphi_para_ios (1)/Barcode.deployproj ./29485_c_243_digo_de_barras_no_delphi_para_ios_1_/Barcode.deployproj
Traceback (most recent call last):
  File "dupimages.py", line 61, in <module>
    main()
  File "dupimages.py", line 34, in main
    os.rename(file, new)
OSError: [Errno 2] No such file or directory

**Comment by buchireddy** [comment]
Thanks for reporting this, @bharath2020 I will look into this.

**Comment by buchireddy** [comment]
Fixed this. @bharath2020 Wanna try again?

**Comment by bharath2020** [comment]
Fixed
